alert("Bienvenido viajero, antes de ingresar deberá responder una serie de preguntas")
var nombre = prompt("¿Cual es su nombre?")
var raza = prompt("¿De que raza eres?")
var tierra = prompt("¿De que tierras proviene?")
var edad = prompt("¿Cuantos inviernos ha padecido?")
var motivo = prompt("¿Que lo trae a estos rincones del mundo?")